import React from 'react';
import Head from 'next/head';
import Header from '../../../components/frontend/Header';
import Banner from '../../../components/contact/Banner';
import ProductDetail from '../../../components/product/ProductDetail';
import prisma from '../../../utils/prisma';

export async function getServerSideProps({ params }) {
    const product = await prisma.product_detail.findMany({
        where: {
            id: params.id
        },
        include: {
            product: true,
            subCategory: true,
            stores: true,
            units: true,
            spesification: true,
        },
    });

    return {
        props: {
            product: JSON.parse(JSON.stringify(product)),
        },
    }
}

const Id = ({ product }) => {
    console.log(product)
    return (
        <div>
            <Head>
                <title>HOSANA GROUP</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="shortcut icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" type="image/vnd.microsoft.icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" type="image/x-icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" href="/assets/favicon/favicon.ico" />
            </Head>
            {/* header Section */}
            <Header />
            {/* Banner Section */}
            <Banner />
            {product.map(item => (
                <ProductDetail key={item.id} id={item.id} title={item.product.title} img={item.product.image} price={item.price} description={item.product.description} quantity={item.product.quantity} subCategory={item.subCategory.name} discount={item.discount} place={item.stores.name} group={item.product.group} unit={item.units.name} 
                titleOne={item.spesification.map(items => items.titleOne)}
                titleTwo={item.spesification.map(items => items.titleTwo)}
                titleThree={item.spesification.map(items => items.titleThree)}
                titleFour={item.spesification.map(items => items.titleFour)}
                titleFive={item.spesification.map(items => items.titleFive)}
                answerOne={item.spesification.map(items => items.answerOne)}
                answerTwo={item.spesification.map(items => items.answerTwo)}
                answerThree={item.spesification.map(items => items.answerThree)}
                answerFour={item.spesification.map(items => items.answerFour)}
                answerFive={item.spesification.map(items => items.answerFive)}
                />
            ))}
        </div>
    );
}

export default Id;
