import { getSession, useSession } from 'next-auth/react';
import Head from 'next/head';
import React, { useEffect, useMemo, useState } from 'react';
import Header from '../../components/admin/Header';
import SideNavbar from '../../layout/SideNavbar';
import Link from "next/link";
import DataTable from 'react-data-table-component';
import CustomLoader from '../../components/CustomLoader';
import { MdDelete } from 'react-icons/md';
import { HiPlusSm } from 'react-icons/hi';

const AboutPage = () => {
    const { data: session } = useSession();
    const [about, setAbout] = useState([]);
    const [pending, setPending] = useState(true);

    const fetchAbout = () => {
        fetch('/api/about/getdata').then(res => res.json().then((data) => {
            setAbout(data)
        }))
    }

    const handleButtonDelete = async (e, id) => {
        e.preventDefault();
        if (confirm('Are you sure want to delete this ?')) {
            try {
                await fetch("/api/about/deletedata?id=" + id, {
                    method: "DELETE",
                    headers: { "Content-Type": "application/json" },
                })
                window.location.reload();
            } catch (err) {
                console.log(err)
            }
        } else {
            console.log("not gonna happen!")
        }
    };

    const column = [
        {
            name: 'Img Banner',
            selector: row => <img height="84px" width="56px" src={row.imgBanner} />,
        },
        {
            name: 'Img Company',
            selector: row => <img height="84px" width="56px" src={row.imgCompany1} />,
        },
        {
            name: 'Img Company',
            selector: row => <img height="84px" width="56px" src={row.imgCompany2} /> ,
        },
        {
            name: 'Img Concept',
            selector: row => <img height="84px" width="56px" src={row.imgConcept} />,
        },
        {
            name: 'Img Class',
            selector: row => <img height="84px" width="56px" src={row.imgClass1} />,
        },
        {
            name: 'Img Class',
            selector: row => <img height="84px" width="56px" src={row.imgClass2} />,
        },
        {
            name: 'Img Class',
            selector: row => <img height="84px" width="56px" src={row.imgClass3} />,
        },
        {
            name: 'Img Class',
            selector: row => <img height="84px" width="56px" src={row.imgClass4} />,
        },
        {
            name: 'Text Company',
            selector: row => row.textCompany1,
        },
        {
            name: 'Text Company',
            selector: row => row.textCompany2,
        },
        {
            name: 'Vision Title',
            selector: row => row.visionTitle,
        },
        {
            name: 'Vision Detail',
            selector: row => row.visionDetail,
        },
        {
            name: 'Mission Title',
            selector: row => row.missionTitle,
        },
        {
            name: 'Mission Detail',
            selector: row => row.missionDetail,
        },
        {
            name: 'Value Detail',
            selector: row => row.valueDetail,
        },
        {
            name: 'Concept Title',
            selector: row => row.conceptTitle,
        },
        {
            name: 'Concept Detail',
            selector: row => row.conceptDetail,
        },
        {
            name: 'Class Title',
            selector: row => row.classTitle,
        },
        {
            name: "Action",
            button: true,
            cell: row =>
            (
                <>
                    <button onClick={(e) => handleButtonDelete(e, row.id)}>
                        <MdDelete className='h-5 w-5' />
                    </button>
                </>
            )
        }
    ];

    useEffect(() => {
        const timeout = setTimeout(() => {
            fetchAbout();
            setPending(false);
        }, 2000);
        return () => clearTimeout(timeout);
    }, [])
    return (
        <>
            <Header />
            <SideNavbar>
                <Head>
                    <title>HOKITO GROUP</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="shortcut icon" href="/assets/favicon/favicon.ico" />
                    <link rel="icon" type="image/vnd.microsoft.icon" href="/assets/favicon/favicon.ico" />
                    <link rel="icon" type="image/x-icon" href="/assets/favicon/favicon.ico" />
                    <link rel="icon" href="/assets/favicon/favicon.ico" />
                </Head>
                <div class="items-center justify-between pb-5 lg:flex xl:flex md:flex">
                    <div className=''>
                        <h1 className="text-2xl font-semibold leading-relaxed text-gray-600">About</h1>
                        <p className="text-sm font-medium text-gray-500">
                            About Detail Here
                        </p>
                    </div>
                    <Link href="/admin/about/create"
                        className="inline-flex gap-x-2 items-center py-2.5 px-6 text-white bg-indigo-600 rounded-lg hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-1"
                    >
                        <HiPlusSm className="w-6 h-6 fill-white" />
                        <span className="text-sm font-semibold tracking-wide">Create About</span>
                    </Link>
                </div>
                <DataTable
                    columns={column}
                    data={about}
                    striped
                    pagination
                    progressPending={pending}
                    progressComponent={<CustomLoader />}
                   
                />
            </SideNavbar>
        </>
    );
}

export default AboutPage;

export async function getServerSideProps({ req }) {
    const session = await getSession({ req })

    if (session?.user.role != "ADMIN") {
        return {
            redirect: {
                destination: "/auth/login",
                permanent: false
            }
        }
    }
    // autorize user
    return {
        props: { session }
    }
}
