import { getSession, useSession } from 'next-auth/react';
import Head from 'next/head';
import React from 'react';
import { BiPlus } from 'react-icons/bi';
import { HiSearch } from 'react-icons/hi';
import Header from '../../components/admin/Header';
import SideNavbar from '../../layout/SideNavbar';
import Link from "next/link";

const CategoryPage = () => {
    const { data: session } = useSession()
    return (
        <>
            <Header />
            <SideNavbar>
                <Head>
                    <title>HOSANA GROUP</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="shortcut icon" href="/assets/favicon/favicon.ico" />
                    <link rel="icon" type="image/vnd.microsoft.icon" href="/assets/favicon/favicon.ico" />
                    <link rel="icon" type="image/x-icon" href="/assets/favicon/favicon.ico" />
                    <link rel="icon" href="/assets/favicon/favicon.ico" />
                </Head>
                <div className='p-5 md:p-8 bg-white shadow rounded mb-8 flex flex-col'>
                    <div className='flex w-full flex-col items-center md:flex-row'>
                        <div className='mb-4 md:mb-0 md:w-1/4'>
                            <h1 className='text-lg text-gray-600 font-medium text-heading'>Categories</h1>
                        </div>
                        <div className='mx-auto flex w-full flex-col items-center space-y-4 md:flex-row md:space-y-0 xl:w-3/4'>
                            <form noValidate role="search" className='relative flex w-full items-center'>
                                <label for="search" className='sr-only'>Search</label>
                                <button type="button" className='col-start-1 absolute p-2 text-base outline-none focus:outline-none active:outline-none'>
                                    <HiSearch className='h-5 w-5 text-gray-300' />
                                </button>
                                <input type="text" name="searchText" id="search" placeholder='Type your query and press enter' aria-label='Search' autoComplete='off' className='px-10 py-4 h-12 flex items-center w-full rounded appearance-none transition duration-300 ease-in-out text-heading text-sm focus:outline-none focus:ring-0 border border-border-base focus:border-accent' />
                            </form>
                            <Link href="" className="inline-flex items-center justify-center flex-shrink-0 text-sm font-semibold leading-none rounded outline-none transition duration-300 ease-in-out focus:outline-none focus:shadow bg-green-400 text-white border border-transparent hover:bg-green-hover px-5 py-0 h-12 md:mx-6 md:w-auto w-full">
                                <span className='block md:hidden xl:block'>
                                    +
                                    Add Categories
                                </span>
                                <span className='hidden md:block xl:hidden'>
                                    +
                                    Add
                                </span>
                            </Link>
                        </div>
                    </div>
                </div>
            </SideNavbar>
        </>
    );
}

export default CategoryPage;

export async function getServerSideProps({ req }) {
    const session = await getSession({ req })

    if (!session) {
        return {
            redirect: {
                destination: "/auth/login",
                permanent: false
            }
        }
    }
    // autorize user
    return {
        props: { session }
    }
}
