import { getSession, useSession } from 'next-auth/react';
import Head from 'next/head';
import React, { useEffect, useMemo, useState } from 'react';
import Header from '../../components/admin/Header';
import SideNavbar from '../../layout/SideNavbar';
import Link from "next/link";
import DataTable from 'react-data-table-component';
import CustomLoader from '../../components/CustomLoader';
import { MdDelete } from 'react-icons/md';
import { HiPlusSm } from 'react-icons/hi';

const ExpiredPoinPage = () => {
    const { data: session } = useSession();
    const [user, setUser] = useState([]);
    const [pending, setPending] = useState(true);

    const fetchUser = () => {
        fetch('/api/expiredpoin/getdata').then(res => res.json().then((data) => {
            setUser(data)
        }))
    }

    const handleButtonDelete = async (e, id) => {
        e.preventDefault();
        if (confirm('Are you sure want to delete this ?')) {
            try {
                await fetch("/api/expiredpoin/deletedata?id=" + id, {
                    method: "DELETE",
                    headers: { "Content-Type": "application/json" },
                })
                window.location.reload();
            } catch (err) {
                console.log(err)
            }
        } else {
            console.log("not gonna happen!")
        }
    };

    const column = [
        {
            name: 'Phone Number',
            selector: row => row.userPhone.number,
        },
        {
            name: 'Total Poin',
            selector: row => row.total_poin,
        },
        {
            name: 'expired Poin',
            selector: row => row.expiredAt,
        },
        {
            name: "Action",
            button: true,
            cell: row =>
            (
                <>
                    <button onClick={(e) => handleButtonDelete(e, row.id)}>
                        <MdDelete className='h-5 w-5' />
                    </button>
                </>
            )
        }
    ];

    useEffect(() => {
        const timeout = setTimeout(() => {
            fetchUser();
            setPending(false);
        }, 2000);
        return () => clearTimeout(timeout);
    }, [])
    return (
        <>
            <Header />
            <SideNavbar>
                <Head>
                    <title>HOKITO GROUP</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="shortcut icon" href="/assets/favicon/favicon.ico" />
                    <link rel="icon" type="image/vnd.microsoft.icon" href="/assets/favicon/favicon.ico" />
                    <link rel="icon" type="image/x-icon" href="/assets/favicon/favicon.ico" />
                    <link rel="icon" href="/assets/favicon/favicon.ico" />
                </Head>
                <div class="items-center justify-between pb-5 lg:flex xl:flex md:flex">
                    <div className=''>
                        <h1 class="text-2xl font-semibold leading-relaxed text-gray-600">Expired Poin</h1>
                        <p class="text-sm font-medium text-gray-500">
                            All Expired Poin here
                        </p>
                    </div>
                    <Link href="/admin/expiredpoin/create"
                        className="inline-flex gap-x-2 items-center py-2.5 px-6 text-white bg-indigo-600 rounded-lg hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-1"
                    >
                        <HiPlusSm className="w-6 h-6 fill-white" />
                        <span className="text-sm font-semibold tracking-wide">Create Expired Poin</span>
                    </Link>
                </div>
                <DataTable
                    columns={column}
                    data={user}
                    striped
                    pagination
                    progressPending={pending}
                    progressComponent={<CustomLoader />}
                   
                />
            </SideNavbar>
        </>
    );
}

export default ExpiredPoinPage;

export async function getServerSideProps({ req }) {
    const session = await getSession({ req })

    if (session?.user.role != "ADMIN") {
        return {
            redirect: {
                destination: "/auth/login",
                permanent: false
            }
        }
    }
    // autorize user
    return {
        props: { session }
    }
}
