import React from 'react';
import SideNavbar from '../../layout/SideNavbar';
import { getSession, useSession } from "next-auth/react";
import { HiPlusSm } from "react-icons/hi";
import { TfiMoney } from "react-icons/tfi";
import { FiUsers } from "react-icons/fi";
import { MdProductionQuantityLimits, MdCategory } from "react-icons/md"
import Head from 'next/head';
import Header from '../../components/admin/Header';
// import prisma from '../../utils/prisma';

const HomePage = () => {
    const { data: session } = useSession()
    return (
        <>
            <Header />
            <SideNavbar>
                <Head>
                    <title>HOSANA GROUP</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="shortcut icon" href="/assets/favicon/favicon.ico" />
                    <link rel="icon" type="image/vnd.microsoft.icon" href="/assets/favicon/favicon.ico" />
                    <link rel="icon" type="image/x-icon" href="/assets/favicon/favicon.ico" />
                    <link rel="icon" href="/assets/favicon/favicon.ico" />
                </Head>
                <div class="grid grid-cols-1 gap-2.5 sm:grid-cols-2 xl:grid-cols-4">
                    <div className='relative flex rounded-lg p-4 bg-white justify-between pb-8'>
                        <div className='flex flex-col'>
                            <span className='mb-1 text-base font-semibold text-heading'>Total Users</span>
                            <span className='text-xs font-semibold text-body'>(30 Days)</span>
                        </div>
                        <div className='flex flex-shrink-0 mx-3 h-12 w-12 justify-center items-center rounded-full bg-green-200'>
                            <FiUsers />
                        </div>
                    </div>
                    <div className='relative flex rounded-lg p-4 bg-white justify-between pb-8'>
                        <div className='flex flex-col'>
                            <span className='mb-1 text-base font-semibold text-heading'>Total Product</span>
                            <span className='text-xs font-semibold text-body'>(30 Days)</span>
                        </div>
                        <div className='flex flex-shrink-0 mx-3 h-12 w-12 justify-center items-center rounded-full bg-green-200'>
                            <MdProductionQuantityLimits />
                        </div>
                    </div>
                    <div className='relative flex rounded-lg p-4 bg-white justify-between pb-8'>
                        <div className='flex flex-col'>
                            <span className='mb-1 text-base font-semibold text-heading'>Total Category</span>
                            <span className='text-xs font-semibold text-body'>(30 Days)</span>
                        </div>
                        <div className='flex flex-shrink-0 mx-3 h-12 w-12 justify-center items-center rounded-full bg-green-200'>
                            <MdCategory />
                        </div>
                    </div>
                    <div className='rounded-lg p-4 bg-white'>
                        <div className='flex pb-8 justify-between'>
                            <div className='flex flex-col'>
                                <span className='mb-1 text-base font-semibold text-heading'>Total Revenue</span>
                                <span className='text-xs font-semibold text-body'>(30 Days)</span>
                            </div>
                            <div className='flex flex-shrink-0 mx-3 h-12 w-12 justify-center items-center rounded-full bg-green-200'>
                                <TfiMoney />
                            </div>
                        </div>
                        <span className='mb-2 text-xl font-semibold text-heading'>500</span>
                    </div>
                </div>
            </SideNavbar >
        </>
    );
}

export default HomePage;


export async function getServerSideProps({ req }) {
    const session = await getSession({ req });
    // console.log(session.user.role)
    if (session?.user.role != "ADMIN") {
        return {
            redirect: {
                destination: "/auth/login",
                permanent: false
            }
        }
    }
    
    // autorize user
    return {
        props: { session }
    }
}