import React from 'react';
import SideNavbar from '../../layout/SideNavbar';
import { getSession, useSession } from "next-auth/react";
import { FiUsers } from "react-icons/fi";
import { MdProductionQuantityLimits, MdCategory } from "react-icons/md"
import Head from 'next/head';
import Header from '../../components/admin/Header';
import prisma from "../../utils/prisma";
import { BiStore } from 'react-icons/bi';

const HomePage = props => {
    const { data: session } = useSession()
    const {category, product, users, store} = props;
    const cat = Boolean(category && category.length);
    const pro = Boolean(product && product.length);
    const usr = Boolean(users && users.length);
    const str = Boolean(store && store.length);
    return (
        <>
            <Header />
            <SideNavbar>
                <Head>
                    <title>HOSANA GROUP</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="shortcut icon" href="/assets/favicon/favicon.ico" />
                    <link rel="icon" type="image/vnd.microsoft.icon" href="/assets/favicon/favicon.ico" />
                    <link rel="icon" type="image/x-icon" href="/assets/favicon/favicon.ico" />
                    <link rel="icon" href="/assets/favicon/favicon.ico" />
                </Head>
                <div className="grid grid-cols-1 gap-2.5 sm:grid-cols-2 xl:grid-cols-4">
                    <div className='rounded-lg p-4 bg-white'>
                        <div className='flex pb-8 justify-between'>
                            <div className='flex flex-col'>
                                <span className='mb-1 text-base font-semibold text-heading'>Total Users</span>
                            </div>
                            <div className='flex flex-shrink-0 mx-3 h-12 w-12 justify-center items-center rounded-full bg-green-200'>
                                <FiUsers />
                            </div>
                        </div>
                        <span className='mb-2 text-xl font-semibold text-heading'>{usr}</span>
                    </div>
                    <div className='rounded-lg p-4 bg-white'>
                        <div className='flex pb-8 justify-between'>
                            <div className='flex flex-col'>
                                <span className='mb-1 text-base font-semibold text-heading'>Total Product</span>
                            </div>
                            <div className='flex flex-shrink-0 mx-3 h-12 w-12 justify-center items-center rounded-full bg-green-200'>
                                <MdProductionQuantityLimits />
                            </div>
                        </div>
                        <span className='mb-2 text-xl font-semibold text-heading'>{pro}</span>
                    </div>
                    <div className='rounded-lg p-4 bg-white'>
                        <div className='flex pb-8 justify-between'>
                            <div className='flex flex-col'>
                                <span className='mb-1 text-base font-semibold text-heading'>Total Category</span>
                            </div>
                            <div className='flex flex-shrink-0 mx-3 h-12 w-12 justify-center items-center rounded-full bg-green-200'>
                                <MdCategory />
                            </div>
                        </div>
                        <span className='mb-2 text-xl font-semibold text-heading'>{cat}</span>
                    </div>
                    <div className='rounded-lg p-4 bg-white'>
                        <div className='flex pb-8 justify-between'>
                            <div className='flex flex-col'>
                                <span className='mb-1 text-base font-semibold text-heading'>Total Store </span>
                            </div>
                            <div className='flex flex-shrink-0 mx-3 h-12 w-12 justify-center items-center rounded-full bg-green-200'>
                                <BiStore />
                            </div>
                        </div>
                        <span className='mb-2 text-xl font-semibold text-heading'>{str}</span>
                    </div>
                </div>
            </SideNavbar >
        </>
    );
}

export default HomePage;


export async function getServerSideProps({ req }) {
    const session = await getSession({ req });
    const category = await prisma.category.findMany();
    const product = await prisma.product.findMany();
    const users = await prisma.user.findMany();
    const store = await prisma.stores.findMany();
    // console.log(session.user.role)
    if (session?.user.role != "ADMIN") {
        return {
            redirect: {
                destination: "/auth/login",
                permanent: false
            }
        }
    }

    // autorize user
    return {
        props: { session, 
            category: JSON.parse(JSON.stringify(category)), 
            product: JSON.parse(JSON.stringify(product)), 
            users: JSON.parse(JSON.stringify(users)), 
            store, 
        }
    }
}