import Head from 'next/head';
import React, { useState } from 'react';
import { FaUpload } from 'react-icons/fa';
import Header from '../../../../components/admin/Header';
import SideNavbar from '../../../../layout/SideNavbar';
import prisma from '../../../../utils/prisma';
import { useRouter } from "next/router";

export async function getServerSideProps({ params }) {
    const users = await prisma.phone_user_poin.findMany({
        where: {
            id: params.id
        }
    });
    return {
        props: {
            user: users,
        },
    }
}

const subCategorybyId = props => {
    const { user } = props;
    const router = useRouter()
    const [userpoin, setUserPoin] = useState(user[0].number)
    //state

    const handleFormData = async (e) => {
        e.preventDefault();
        const id = user[0].id;
        const res = await fetch("/api/userpoin/editdata", {
            method: "PUT",
            body: JSON.stringify({
                number: userpoin,
                id: id
            }),
            headers: {
                'Content-Type': 'application/json',
            }
        });
        const result = await res.json();
        router.push("/admin/userPoinPage")
    }

    return (
        <>
            <Header />
            <SideNavbar>
                <Head>
                    <title>HOSANA GROUP</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="shortcut icon" href="/assets/favicon/favicon.ico" />
                    <link rel="icon" type="image/vnd.microsoft.icon" href="/assets/favicon/favicon.ico" />
                    <link rel="icon" type="image/x-icon" href="/assets/favicon/favicon.ico" />
                    <link rel="icon" href="/assets/favicon/favicon.ico" />
                </Head>
                {/* Category */}
                <section>
                    <div className='flex border-b border-dashed border-border-base py-5 sm:py-8'>
                        <h1 className='text-lg font-semibold text-heading'>Edit SubCategory</h1>
                    </div>
                    <form onSubmit={handleFormData}>
                        <div className='my-5 flex flex-wrap sm:my-8'>
                            <div className='w-full px-0 pb-5 sm:w-4/12 sm:py-8 sm:px-4 md:w-1/3 md:py-5'>
                                <h4 className='text-base font-semibold mb-2'>Details</h4>
                                <p className='text-sm'>Add Category and Subcategory from here</p>
                            </div>
                            <div className='p-5 md:p-8 bg-white shadow rounded w-full sm:w-8/12 md:w-2/3'>
                                <div className='mb-5'>
                                    <label for="number" className='block mb-3 text-sm font-normal leading-none text-gray-400'>Number</label>
                                    <input type="text" inputmode="numeric" pattern="[0-9]*" value={userpoin} onChange={e => setUserPoin(e.target.value)} name="number" id="number" className='px-4 h-12 flex items-center w-full rounded appearance-none transition duration-300 ease-in-out text-heading text-sm focus:outline-none focus:ring-0 border border-border-base focus:border-accent'/>
                                </div>
                            </div>
                        </div>
                        <div className='mb-4 text-end'>
                            <button type="submit" className='inline-flex items-center justify-center flex-shrink-0 font-normal leading-none rounded outline-none transition duration-300 ease-in-out focus:outline-none focus:shadow focus:ring-1 focus:ring-accent-700 bg-green-400 text-white border border-transparent hover:bg-accent-hover px-5 py-0 h-12'>Edit User Poin</button>
                        </div>
                    </form>
                </section>
            </SideNavbar>
        </>
    );
}

export default subCategorybyId;    
