import React from 'react';
import prisma from '../../utils/prisma';
import Head from 'next/head';
import Header from '../../components/frontend/Header';
import Banner from '../../components/contact/Banner';
import ProductCard from '../../components/ProductCard';

export async function getServerSideProps({ params }) {
    const product = await prisma.product_detail.findMany({
        where: {
            subCategoryId: params.id
        },
        include: {
            product: {
                select: {
                    title: true,
                    description: true,
                    quantity: true,
                    image: true,
                    group: true,
                    productImage: true
                }
            },
            subCategory: true,
            stores: true,
            units: true,
            spesification: true,
        },
    });
    const catName = await prisma.subCategoryThird.findMany({
        where: {
            id: params.id
        }
    })

    return {
        props: {
            product: JSON.parse(JSON.stringify(product)),
            catName
        },
    }
}

const Id = ({ product, catName }) => {
    console.log(catName)
    return (
        <div>
            <Head>
                <title>HOSANA GROUP</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="shortcut icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" type="image/vnd.microsoft.icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" type="image/x-icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" href="/assets/favicon/favicon.ico" />
            </Head>
            {/* header Section */}
            <Header />
            {/* Banner Section */}
            <Banner />
            <section className='pt-10'>
            <h2 className='text-4xl font-thin pb-3 text-center mb-10'>{catName.map(items => items.name)}</h2>
                <div className="group relative md:-ml-2">
                    <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>

                        {product.map(item => (
                            <ProductCard key={item.id} id={item.id} title={item.product.title} img={item.product.image} price={item.price} description={item.product.description} quantity={item.product.quantity} subCategory={item.subCategory.name} discount={item.discount} place={item.stores.name} group={item.product.group} unit={item.units.name} />
                        ))}
                    </div>
                </div>
            </section>
        </div>
    );
}

export default Id;
