-- CreateTable
CREATE TABLE `customer_poin` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `loc` VARCHAR(191) NULL,
    `ar_type` VARCHAR(191) NULL,
    `ar_no` VARCHAR(191) NULL,
    `ar_date` VARCHAR(191) NULL,
    `due_date` VARCHAR(191) NULL,
    `cust_code` VARCHAR(191) NULL,
    `total_ar` BIGINT NULL,
    `payment` BIGINT NULL,
    `giro_rls` INTEGER NULL,
    `description` VARCHAR(191) NULL,
    `giro_no` INTEGER NULL,
    `ar_notemp` VARCHAR(191) NULL,
    `ac_code` INTEGER NULL,
    `seri_id` INTEGER NULL,
    `status` VARCHAR(191) NULL,
    `flag_gl` VARCHAR(191) NULL,
    `flag_giro` INTEGER NULL,
    `status_giro` VARCHAR(191) NULL,
    `giro` INTEGER NULL,
    `flag_gl_cair` VARCHAR(191) NULL,
    `ac_biaya` INTEGER NULL,
    `biaya` INTEGER NULL,
    `cust_name` VARCHAR(191) NULL,
    `sales_code` VARCHAR(191) NULL,
    `sisa` BIGINT NULL,
    `phone1` BIGINT NULL,
    `due` INTEGER NULL,
    `jual` BIGINT NULL,
    `retur_panjar` INTEGER NULL,
    `periode` INTEGER NULL,
    `keterangan` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
