import Head from "next/head";
import Banner from "../components/about/Banner";
import CardAbout from "../components/about/CardAbout";
import Profile from "../components/about/Profile";
import Quality from "../components/about/Quality";
import Footer from "../components/Footer";
import Header from "../components/frontend/Header";

const About = () => {
    return (
        <div>
            <Head>
                <title>HOSANA GROUP - ABOUT</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="shortcut icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" type="image/vnd.microsoft.icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" type="image/x-icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" href="/assets/favicon/favicon.ico" />
            </Head>
            <Header />
            <Banner />
            <main className='max-w-7xl mx-auto px-2 sm:px-16'>
                {/* company Profile */}
                <section className="grid grid-cols-1 lg:grid-cols-2 sm:grid-cols-1 py-5 gap-2.5">
                    <Profile />
                </section>
                <section className="pt-5">
                    <div className="relative text-center justify-center items-center">
                        <h5 className='font-medium justify-center text-lg tracking-widest pb-2'>Vision of Hosana Kito Group</h5>
                        <h2 className='font-semibold text-3xl pt-2 tracking-wide'>Most Complete and Competitive</h2>
                        <p className='pt-5 text-sm leading-7 px-10 lg:px-60 xl:px-60'>As a building material center with imported and local products, the most complete and competitive prices & become a market leader in its field.</p>
                    </div>
                    <div className="relative text-center justify-center items-center pt-5">
                        <h5 className='font-medium justify-center text-lg tracking-widest pb-2'>Hosana Kito Group Mission</h5>
                        <h2 className='font-semibold text-3xl pt-2 tracking-wide'>Complete Product and Best Quality</h2>
                        <p className='pt-5 text-sm leading-7 px-10 lg:px-60 xl:px-60'>Determined to be the most complete ceramic sales center and building materials that can provide quality goods, competitive prices, as trendsetters, always up to date, innovation and have resources that are knowledgeable, high performance and oriented to customer satisfaction.</p>
                    </div>

                    <div className='justify-center items-center text-center pt-5'>
                        <h5 className='font-medium justify-center text-lg tracking-widest pb-2'>Hosana Kito Group Product Classification is divided into 4 (four), namely:</h5>
                    </div>
                    <div className="pt-2 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 py-5 gap-2.5 justify-items-center">
                        <CardAbout />
                    </div>

                    <div className="relative text-center justify-center items-center pt-5">
                        <h5 className='font-medium justify-center text-lg tracking-widest pb-2'>Hosana Kito Group Value</h5>
                        <p className='pt-5 text-sm leading-7 px-10 lg:px-60 xl:px-60'>CSR (Corporate Social Responsibility) is oriented towards environmental, social and cultural concerns.</p>
                        <p className='pt-5 text-sm leading-7 px-10 lg:px-60 xl:px-60'>Profit & Welfare, namely achieving balanced welfare between companies and employees, faithful and modern.</p>
                    </div>
                </section>
                <section className="grid grid-cols-1 lg:grid-cols-2 sm:grid-cols-1 py-5 gap-2.5">
                    <Quality />
                </section>
            </main>
            <Footer />
        </div>
    );
}

export default About;
