import Head from "next/head";
import Banner from "../components/about/Banner";
import CardAbout from "../components/about/CardAbout";
import Profile from "../components/about/Profile";
import Quality from "../components/about/Quality";
import Footer from "../components/Footer";
import Header from "../components/frontend/Header";
import prisma from "../utils/prisma";


const About = ({ about }) => {
    return (
        <div>
            <Head>
                <title>HOKITO GROUP - ABOUT</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="shortcut icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" type="image/vnd.microsoft.icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" type="image/x-icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" href="/assets/favicon/favicon.ico" />
            </Head>
            <Header />
            {about.map(item => (
                <>
                    <Banner img={item.imgBanner} />
                    <main className='max-w-7xl mx-auto px-2 sm:px-16'>
                        {/* company Profile */}
                        <section className="grid grid-cols-1 lg:grid-cols-2 sm:grid-cols-1 py-5 gap-2.5">
                            <Profile img1={item.imgCompany1} img2={item.imgCompany2} title1={item.textCompany1} title2={item.textCompany2} />
                        </section>
                        <section className="pt-5">
                            <div className="relative text-center justify-center items-center">
                                <h5 className='font-medium justify-center text-lg tracking-widest pb-2'>Vision of Hosana Kito Group</h5>
                                <h2 className='font-semibold text-3xl pt-2 tracking-wide'>{item.visionTitle}</h2>
                                <p className='pt-5 text-sm leading-7 px-10 lg:px-60 xl:px-60'>{item.visionDetail}</p>
                            </div>
                            <div className="relative text-center justify-center items-center pt-5">
                                <h5 className='font-medium justify-center text-lg tracking-widest pb-2'>Hosana Kito Group Mission</h5>
                                <h2 className='font-semibold text-3xl pt-2 tracking-wide'>{item.missionTitle}</h2>
                                <p className='pt-5 text-sm leading-7 px-10 lg:px-60 xl:px-60'>{item.missionDetail}</p>
                            </div>

                            <div className='justify-center items-center text-center pt-5'>
                                <h5 className='font-medium justify-center text-lg tracking-widest pb-2'>{item.classTitle}</h5>
                            </div>
                            <div className="pt-2 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 py-5 gap-2.5 justify-items-center">
                                <CardAbout img1={item.imgClass1} img2={item.imgClass2} img3={item.imgClass3} img4={item.imgClass4} title1={item.classTitle1} title2={item.classTitle2} title3={item.classTitle3} title4={item.classTitle4} detail1={item.classDetail1} detail2={item.classDetail2} detail3={item.classDetail3} detail4={item.classDetail4} />
                            </div>

                            <div className="relative text-center justify-center items-center pt-5">
                                <h5 className='font-medium justify-center text-lg tracking-widest pb-2'>Hosana Kito Group Value</h5>
                                <p className='pt-5 text-sm leading-7 px-10 lg:px-60 xl:px-60'>{item.valueDetail}</p>

                            </div>
                        </section>
                        <section className="grid grid-cols-1 lg:grid-cols-2 sm:grid-cols-1 py-5 gap-2.5">
                            <Quality img={item.imgConcept} title={item.conceptTitle} detail={item.conceptDetail} />
                        </section>
                    </main>
                </>
            ))}
            <Footer />
        </div>
    );
}

export default About;

export async function getServerSideProps() {
    const about = await prisma.about.findMany({})
    return {
        props: {
            about: JSON.parse(JSON.stringify(about)),
        }
    }
}

