import Head from "next/head";
import Banner from "../components/about/Banner";
import CardAbout from "../components/about/CardAbout";
import Profile from "../components/about/Profile";
import Quality from "../components/about/Quality";
import Footer from "../components/Footer";
import Header from "../components/frontend/Header";

const About = () => {
    return (
        <div>
            <Head>
                <title>HOSANA GROUP - ABOUT</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="shortcut icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" type="image/vnd.microsoft.icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" type="image/x-icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" href="/assets/favicon/favicon.ico" />
            </Head>
            <Header />
            <Banner />
            <main className='max-w-7xl mx-auto px-2 sm:px-16'>
                {/* company Profile */}
                <section className="grid grid-cols-1 lg:grid-cols-2 sm:grid-cols-1 py-5 gap-2.5">
                    <Profile />
                </section>
                <section className="pt-5">
                    <div className="relative text-center justify-center items-center">
                        <h5 className='font-medium justify-center text-lg tracking-widest pb-2'>About Hosana Kito Group</h5>
                        <h2 className='font-semibold text-3xl pt-2 tracking-wide'>Most Complete Range of Products</h2>
                        <p className='pt-5 text-sm leading-7 px-10 lg:px-60 xl:px-60'>To achieve customer satisfaction, we have the most complete range of quality products with innovative design and technology at their comfort and ease:</p>
                        <p className='pt-4 text-sm px-10 lg:px-60 xl:px-60 leading-7'>Our product are categorized into 2 segments: fitting products and sanitary products. For fitting products we have mixer faucet, cold faucet, shower, supplementary fitting, and accessories. For sanitary products we have washbasin, kitchen sink, urinal and toilet.</p>
                        <p className='pt-4 text-sm px-10 lg:px-60 xl:px-60 leading-7'>We also prioritize our long term relationship with our customer based on safety, quality, timely service and highly anticipation of their needs and wants.</p>
                    </div>
                    <div className="pt-10 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 py-5 gap-2.5 justify-items-center">
                         <CardAbout/>
                    </div>
                </section>
                <section className="grid grid-cols-1 lg:grid-cols-2 sm:grid-cols-1 py-5 gap-2.5">
                    <Quality />
                </section>
            </main>
            <Footer />
        </div>
    );
}

export default About;
