import Head from 'next/head';
import React from 'react';
import Banner from '../components/contact/Banner';
import ContactInfo from '../components/contact/ContactInfo';
import Footer from '../components/Footer';
import Header from '../components/frontend/Header';

const Contact = () => {
    return (
        <div>
            <Head>
                <title>HOSANA GROUP - CONTACT</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="shortcut icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" type="image/vnd.microsoft.icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" type="image/x-icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" href="/assets/favicon/favicon.ico" />
            </Head>
            <Header />
            <Banner /> 
            <main className='max-w-7xl mx-auto px-2 sm:px-16'>
                <section className='pt-10 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 py-5 gap-2.5 justify-items-center'>
                    <ContactInfo />
                </section>
            </main>
            <Footer/>
        </div>
    );
}

export default Contact;
