import Head from 'next/head'
import Banner from '../components/Banner'
import Category from '../components/Category'
import Footer from '../components/Footer'
import Header from '../components/Header'
import LargeCard from '../components/LargeCard'
import ProductCard from '../components/ProductCard'
import { PrismaClient, Prisma } from '@prisma/client';

const prisma = new PrismaClient();

export default function Home({products, categories}) {

  return (
    <div className>
      <Head>
        <title>HOSANA GROUP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/kitohosana.jpg" />
      </Head>
      {/* header Section */}
      <Header />

      {/* Banner Section */}
      <Banner />

      {/* Category Section */}
      <main className='max-w-7xl mx-auto px-8 sm:px-16'>
        <section className='pt-6'>
          <h2 className='text-4xl font-semibold pb-5'>Category</h2>
          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
            {categories.map(item =>(
              <Category key={item.id} img={item.img} title={item.title} description={item.description} company={item.company}/>
            ))}
          </div>
        </section>

        <section>
          <h2 className='text-4xl font-semibold py-8'>All Product</h2>
          <div className='flex space-x-3 overflow-scroll scrollbar-hide p-3 ml-3'>
            {products.map(item => (
              <ProductCard key={item.id} title={item.title} img={item.img}/>
            ))}
          </div>
        </section>

        <LargeCard 
          img='/assets/home.jpg'
          title="Greatest Shopping Place In Medan"
          description="Wishlists created by Hosana Group."
          buttonText="Get Inspired"
        />
      </main> 

      {/* footer section */}
      <Footer />
    </div>
  )
}

export async function getServerSideProps() {
  const products = await prisma.product.findMany();
  const categories = await prisma.category.findMany();
  console.log(categories)
  return {
    props: {
       products,
       categories,
    }
  };
} 
