import Head from 'next/head';
import React from 'react';
import Footer from '../components/Footer';
import Header from '../components/frontend/Header';
import Banner from '../components/shop/Banner';

const Shop = () => {
    return (
        <div>
            <Head>
                <title>HOSANA GROUP</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="shortcut icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" type="image/vnd.microsoft.icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" type="image/x-icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" href="/assets/favicon/favicon.ico" />
            </Head>
            <Header/>
            <Banner/>
            <Footer/>
        </div>
    );
}

export default Shop;
