import Header from "../components/frontend/Header"
import Footer from "../components/Footer"
import LargeCard from "../components/LargeCard";
import Head from "next/head";
import Banner from "../components/about/Banner";
import Address from "../components/store/Address";


const store = () => {
  return (
    <div>
      <Head>
        <title>HOKITO GROUP - STORE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/assets/favicon/favicon.ico" />
        <link rel="icon" type="image/vnd.microsoft.icon" href="/assets/favicon/favicon.ico" />
        <link rel="icon" type="image/x-icon" href="/assets/favicon/favicon.ico" />
        <link rel="icon" href="/assets/favicon/favicon.ico" />
      </Head>
      <Header />
      <Banner/>
      <div className="max-w-7xl mx-auto px-8 sm:px-16">
        <div className="pt-6">
          <Address />
        </div>
      </div>
      <Footer />
    </div>
  )
}

export default store;