import Head from 'next/head';
import React from 'react';
import Banner from '../../components/customer/Banner';
import TableRedeem from '../../components/customer/TableRedeem';
import Header from '../../components/frontend/Header';
import prisma from '../../utils/prisma';

const Redeem = ({userPhone}) => {
    return (
        <div className='w-[600px] md:w-full lg:w-full sm:w-full'>
            <Head>
                <title>HOSANA GROUP</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="shortcut icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" type="image/vnd.microsoft.icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" type="image/x-icon" href="/assets/favicon/favicon.ico" />
                <link rel="icon" href="/assets/favicon/favicon.ico" />
            </Head>
            {/* header Section */}
            <Header />
            <Banner />

            <main className='max-w-7xl mx-auto px-2 sm:px-16'>
                <section className='pt-10'>
                    <h2 className='text-4xl font-thin pb-3 text-center'>Redeem</h2>
                    <TableRedeem redeem={userPhone} />
                </section>
            </main>
            </div>
    );
}

export default Redeem;

export async function getServerSideProps(context) {
    // console.log(context.query.q)
    const userPhone = await prisma.redeem.findMany({
        where:{
            userId: context.query.q
        },
        select: {
            id: true,
            total_poin: true,
            expiredAt: true,
            redeem_poin: true,
            users: {
                select:{
                    phone: true
                }
            }
        }
    })

    // autorize user
    return {
        props: { userPhone }
    }
}
